<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDt2oeKF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDt2oeKF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDt2oeKF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDt2oeKF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDt2oeKF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dt2oeKF',
    'container.build_id' => '6a1a4278',
    'container.build_time' => 1683188189,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDt2oeKF');
